title: Amogh Raut
logo: /assets/img/profile.jpg
description: ML enthusiast | IIT BHU Graduate
show_downloads: false
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID

# Social Links
github_username: AmoghRaut
linkedin: https://www.linkedin.com/in/amogh-raut-4288a4264/
email: rautamogh3@gmail.com