title: Amogh Raut
logo: /assets/img/profile.jpg
description: ML Research Assistant | IIT Varanasi Graduate
show_downloads: false
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID

# Social Links
github_username: 
linkedin: 
email: rautamogh3@gmail.com